"""
Composition strategies for the Colossus Architectures.
Key modules of composition:
1. macro-architecture:
1a. ColossusSucessiveHalfing: Follows FasterVit
1b. ColossusMultiScale: Reuse multi-scale features from
    Apollo/Atlas
2. readout:
2a: MergeAll: Average features across all scales
2b. ClsXattn: use cls token with x-attn for prediction
"""
import math
import logging
from einops import rearrange
import torch
import torch.nn as nn
from .msa import AtlasMultiScale

logger = logging.getLogger(__name__)


class ColossusMultiScale(nn.Module):
    def __init__(
        self,
        args,
        kwargs_list,
        embed_dim=384,
        num_classes=100,
        fc_norm=nn.LayerNorm,
        multiscale_feats=True,
        **kwargs,
    ):
        super().__init__()
        logger.debug(f"Initializing ColossusMultiScale with {len(kwargs_list)} stages.")
        assert kwargs_list is not None, "kwargs_list should be provided"
        self.args = args
        self.kwargs_list = kwargs_list
        self.num_classes = num_classes
        self.image_size = 256
        self.multiscale_feats = multiscale_feats
        logger.debug(f"  Multiscale features enabled: {self.multiscale_feats}")

        atlas_models = [AtlasMultiScale(args=args, **kwargs) for kwargs in kwargs_list]
        self.atlas_models = nn.ModuleList(atlas_models)

        self.embed_dim = embed_dim
        self.readout = "avg"
        logger.debug(f"  Using readout strategy: {self.readout}")

        self.readout_norm = nn.LayerNorm(self.embed_dim)
        logger.debug(f"  Initialized readout_norm: LayerNorm({self.embed_dim})")

        self.fc_norm = nn.LayerNorm(self.embed_dim) if fc_norm else nn.Identity()
        logger.debug(f"  Initialized fc_norm: {self.fc_norm}")

        self.maxpool = nn.AdaptiveMaxPool1d(1)

        self.fc = nn.Linear(self.embed_dim, num_classes)
        logger.debug(f"  Initialized fc head: Linear({self.embed_dim}, {num_classes})")

    def forward_head(self, x, pre_logits: bool = False, scales=None):
        input_shapes = [s.shape for s in x]
        logger.debug(f"Entering forward_head with {len(x)} scales. Shapes (BNC): {input_shapes}")

        # collect features from relevant scales
        if scales is None:
            scales = range(len(x))

        feats = [x[i] for i in scales]
        feats_BNC = torch.cat(feats, dim=1)

        logger.debug(f"  Concatenated features shape (BNC): {feats_BNC.shape}")
        # normalize the inputs
        if isinstance(self.readout_norm, nn.LayerNorm):
            x_BNC = self.readout_norm(feats_BNC)
            logger.debug(f"  Shape after readout_norm: {x_BNC.shape}")
        else:
            x_BNC = feats_BNC

        if self.readout == "avg":
            x_BC = x_BNC.mean(dim=1)
            logger.debug(f"  Shape after mean pooling (BC): {x_BC.shape}")
        else:
            raise NotImplementedError

        x_BC = self.fc_norm(x_BC)
        logger.debug(f"  Shape after fc_norm: {x_BC.shape}")
        if pre_logits:
             logger.debug(f"  Returning pre-logits.")
             return x_BC
        else:
            out = self.fc(x_BC)
            logger.debug(f"  Shape after final fc layer: {out.shape}")
            return out


    def forward(self, x, batch=None):
        # breakpoint()
        base_model = self.atlas_models[0]
        bsz = x.shape[0]

        # raw_shapes = [s.shape for s in x]
        # logger.debug(f"Raw tokens generated by base model. Shapes: {raw_shapes}")

        x = base_model.forward_raw(x)
        layouts = base_model.multiscale_layout
        num_stages = len(self.atlas_models)

        multi_scale_outs = []

        for level, atlas_model in enumerate(self.atlas_models):
            # logger.debug(f"Entering Colossus Stage {level}/{num_stages-1}")
            is_last = len(x) == 1 or level == num_stages - 1
            grid_sizes = [layout["grid_size"] for layout in layouts]
            # forward_features is part of AtlasMultiScale and should log internally
            x = atlas_model.forward_features(
                x, grid_sizes=grid_sizes, process_readout=False
            )
            # stage_output_shapes = [s.shape for s in x]
            # logger.debug(f"Colossus Stage {level} output shapes (before potential drop): {stage_output_shapes}")

            if not is_last:
                multi_scale_outs.append(x[0])
                layouts = layouts[1:]
                x = x[1:]
                # logger.debug(f"Dropped finest scale. Remaining scales: {len(x)}. Updated layouts: {len(layouts)}")
            else:
                logger.debug(f"This is the last stage ({level}).")
        
        multi_scale_outs.append(x[0])
        layouts = base_model.multiscale_layout

        # logger.debug("Preparing features for readout head.")
        # Rearrange from (B*NW, WinSize, C) or (B, N, C) to (B, N_total, C)
        feats_for_head = []
        for i, scale_tokens in enumerate(multi_scale_outs):
            # Need to know if scale_tokens is windowed (B*NW, K, C) or flattened (B, N, C)
            # Assuming it's (B*NW, K, C) if NW > 1 based on layout
            if math.prod(layouts[i]['grid_size']) > 1 and len(scale_tokens.shape) == 3: # Check if likely windowed format
                rearranged_scale = rearrange(scale_tokens, "(b nw) k c -> b (nw k) c", b=bsz)
                logger.debug(f"  Rearranging scale {i} (windowed) {scale_tokens.shape} -> {rearranged_scale.shape}")
                feats_for_head.append(rearranged_scale)
            elif len(scale_tokens.shape) == 3 and scale_tokens.shape[0] == bsz: # Already (B, N, C)
                logger.debug(f"  Using scale {i} (already BNC) shape: {scale_tokens.shape}")
                feats_for_head.append(scale_tokens)
            else:
                logger.warning(f"  Unexpected shape for scale {i}: {scale_tokens.shape}. Attempting BNC rearrange.")
                # Try a generic rearrange, might fail if batch dim isn't divisible
                try:
                    rearranged_scale = rearrange(scale_tokens, "(b nw) k c -> b (nw k) c", b=bsz)
                    feats_for_head.append(rearranged_scale)
                except Exception as e:
                    logger.error(f"    Failed to rearrange scale {i}: {e}. Skipping this scale for readout.")
                    continue


        if self.multiscale_feats:
            x = []
            for i, scale in enumerate(feats_for_head):
                feats = self.maxpool(scale.transpose(1, 2)).squeeze(2)
                x.append(feats)
            x = torch.cat(x, dim=1)
        else:
            ## return maxpool on last scale features only
            x = feats_for_head[0]        
            x = self.maxpool(x.transpose(1, 2)).squeeze(2)
        return x

        ## if you want to use the readout head
        # # forward_head logs internally
        # x = self.forward_head(feats_for_head)
        # logger.info(f"Final output logit shape: {x.shape}")
        # return {"logit": x}




